### ISSUE TITLE
4.12.0 checklist for bundle creation

### ISSUE THREAD

**Issue by praveenkumar** [crc-org/snc#608]
- [x] Not issue from OCP side but looks like something change around how to update kubelet systemd reserved settings.  
    https://issues.redhat.com/browse/OCPBUGS-3758
  - [x] Start using capabilities (instead modifying the CVO resources)  
    https://github.com/openshift/installer/blob/master/docs/user/customization.md#capabilities 
  - [x] Use of infrastructure type  
    https://github.com/openshift/api/blob/master/config/v1/types_infrastructure.go#L84-L103

**Comment by praveenkumar** [comment]
>  Use of infrastructure type

This is already part of infrastructure status
```yaml
$ oc get infrastructures.config.openshift.io -oyaml
apiVersion: v1
items:
- apiVersion: config.openshift.io/v1
  kind: Infrastructure
  metadata:
    creationTimestamp: "2022-11-14T13:42:57Z"
    generation: 1
    name: cluster
    resourceVersion: "524"
    uid: 419d2368-9f74-4c04-a6aa-0fc0eb02cafb
  spec:
    cloudConfig:
      name: ""
    platformSpec:
      type: Libvirt
  status:
    apiServerInternalURI: https://api-int.crc.testing:6443
    apiServerURL: https://api.crc.testing:6443
    controlPlaneTopology: SingleReplica
    etcdDiscoveryDomain: ""
    infrastructureName: crc-529qn
    infrastructureTopology: SingleReplica
    platform: Libvirt
    platformStatus:
      type: Libvirt
kind: List
metadata:
  resourceVersion: ""
```

**Comment by praveenkumar** [comment]
We are able to create rc6 bundle without any issue.
